name = "MetaArrays"
uuid = "36b8f3f0-b776-11e8-061f-1f20094e1fc8"
authors = ["David Little <david.frank.little@gmail.com>"]
version = "0.1.2"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
